#!/bin/bash
# Neofetch: A command-line system information tool written in bash 3.2+.
# https://github.com/dylanaraps/neofetch
# add the following ASCII art to /usr/bin/neofetch
	"Omega"*)
            set_colors 1
            read -rd '' ascii_data <<'EOF'
${c1}




  ⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀  ⣠⣤⣶⣾⣿⣿⣷⣶⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
     ⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀
⠀   ⠀  ⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⣿⣿⠿⠿⢿⣿⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀
⠀⠀ ⠀  ⠀  ⠀⣼⣿⣿⣿⡿⠟⠉⠀⠀⠀⠀⠀⠀⠉⠙⢿⣿⣿⣿⣿⡄⠀⠀⠀⠀
  ⠀ ⠀⠀  ⠀⣸⣿⣿⣿⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⣿⣿⣿⣷⠀⠀⠀⠀
  ⠀⠀   ⠀⠀⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⣿⠀⠀⠀⠀
     ⠀⠀⠀⠀⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀
   ⠀  ⠀⠀⠀⢹⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⠀⠀⠀⠀
     ⠀⠀⣶⣄⠀⢿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⠃⣀⣴⡇⠀
    ⠀ ⠀⣿⣿⣿⣾⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⣿⣿⣷⣾⣿⣿⡇⠀
  ⠀⠀   ⠿⠿⠿⠿⠿⠿⠿⠿⠷⠄⠀⠀⠀⠀⠀⠀⠠⠴⠿⠿⠿⠿⠿⠿⠿⠿⠇⠀
EOF
	;;
