;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   to learn more about how to configure polybar
;   go to https://github.com/polybar/polybar
;
;   the readme contains a lot of information
;
;==========================================================
;aurora borealis themed polybar configuration

[colors]
transparent = #00
white = #ffffff
black = #000000

color0 = #d9303e
color1 = #1e2626
color2 = #81a6a6
color3 = #b4d2d9
color4 = #455959

background = ${colors.color1}
highlight = ${colors.color2}
special = ${colors.color0}
bright = ${colors.color3}
fade = ${colors.color4}

[bar/main]
width = 98.8%
offset-x = 0.7%
offset-y = 1%
height = 24pt
radius = 10
bottom = true
fixed-center = false

; dpi = 96

; bar colors
background = ${colors.background}
foreground = ${colors.white}
border-color = ${colors.special}

line-size = 0
border-top-size = 0

padding-left = 3
padding-right = 3

module-margin = 1

separator = |
separator-foreground = ${colors.background}
separator-padding = 0

font-0 = noto sans:style=regular:size=10.5;2
font-1 = symbols nerd font mono:style=regular:size=10;2

modules-left = xworkspaces show-desk skippy-xd zzzfm-preferences control-center file-manager trash-bin neovim mongodb-compass postman google-chrome youtube icewm-manager
modules-center = active-window
modules-right = unplug-drive battery filesystem memory cpu pulseaudio popup-calendar time power-menu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; ----------------------------------------------------------------------------------------

[module/xworkspaces]
type = internal/xworkspaces

icon-default = ""

label-active = ""
label-active-background = ${colors.background}
label-active-foreground = ${colors.bright}
label-active-underline= ${colors.background}
label-active-padding = 1

label-occupied = ""
label-occupied-foreground = ${colors.bright}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-background = ${colors.special}
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.bright}
label-empty-padding = 1

; ----------------------------------------------------------------------------------------

[module/xwindow]
type = internal/xwindow
format = <label>
label = %class:0:60:...%
; label-maxlen = 15 
label-empty = 

; ----------------------------------------------------------------------------------------

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{f#81a6a6} %mountpoint%%{f-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.fade}

; ----------------------------------------------------------------------------------------

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "󰌡  "
format-volume-prefix-foreground = ${colors.highlight}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = " 󰖁  "
label-muted-foreground = ${colors.fade}

; interval for volume increase/decrease (in percent points)
; default: 5
interval = 2

; right and middle click
click-right = pavucontrol
; click-middle = 

; ----------------------------------------------------------------------------------------

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.highlight}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.transparent}
label-indicator-background = ${colors.white}

; ----------------------------------------------------------------------------------------

[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.highlight}
label = %percentage_used:2%%

; ----------------------------------------------------------------------------------------

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
format-prefix-foreground = ${colors.highlight}
label = %percentage:2%%

; ----------------------------------------------------------------------------------------

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected
format-disconnected = <label-disconnected>
label-disconnected = %{f#f0c674}%ifname%%{f#707880} disconnected

; ----------------------------------------------------------------------------------------

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{f#f0c674}%ifname%%{f-} %essid% %local_ip%

; ----------------------------------------------------------------------------------------

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{f#f0c674}%ifname%%{f-} %local_ip%

; ----------------------------------------------------------------------------------------

[module/time]
type = internal/date
interval = 1

; date = %a, %d %h
; date-alt = %d %b %y 
time = %l:%m %p
time-alt = %l:%m:%s %p

format-prefix = " "
label = %time%
label-background= ${colors.background}
format-prefix-foreground = ${colors.highlight}

; ----------------------------------------------------------------------------------------

[module/popup-calendar]
format-prefix = "|    󰸗 "
format-prefix-foreground = ${colors.highlight}
type = custom/script
exec = ~/.config/polybar/scripts/popup-calendar.sh
interval = 5
click-left = ~/.config/polybar/scripts/popup-calendar.sh --popup &

; ----------------------------------------------------------------------------------------

[settings]
screenchange-reload = true
pseudo-transparency = true

; ----------------------------------------------------------------------------------------

[module/system-usb-udev]
type = custom/script
exec = ~/.config/polybar/scripts/system-usb-udev.sh
tail = true
click-left = ~/.config/polybar/scripts/system-usb-udev.sh --mount &
click-right = ~/.config/polybar/scripts/system-usb-udev.sh --unmount &

; ----------------------------------------------------------------------------------------

[module/power-menu]
type = custom/script
exec = echo "⏻"
format = <label>
label-foreground = ${colors.special}
click-left = /usr/local/bin/desktop-session-exit

; [module/temp]
; type = internal/temperature
; interval = 3
; thermal-zone = 0
; hwmon-path = /sys/class/hwmon/hwmon1/temp1_input
; base-temperature = 36 
; warn-temperature = 60
; units = true

; format =<label>
; format-prefix = " "
; format-prefix-foreground= ${colors.primary}

; label = %temperature-c%
; label-foreground = ${colors.white}
; label-padding-left=2
; label-padding-right=2

; format-warn-prefix = " "
; format-warn-prefix-foreground= ${colors.red}

; label-warn = %temperature-c%
; label-warn-foreground = ${colors.red}
; label-warn-padding-left=2
; label-warn-padding-right=2

; ----------------------------------------------------------------------------------------

[module/active-window]
type = custom/script
format-background = ${colors.background}
format-foreground = ${colors.white}
format-padding = 1
exec = ~/.config/polybar/scripts/active-window.sh
interval = 1

; ----------------------------------------------------------------------------------------

[module/zzzfm-preferences]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = zzzfm --desktop-pref

; ----------------------------------------------------------------------------------------

[module/show-desk]
type = custom/script
exec = echo "|     "
format = <label>
label-foreground = ${colors.highlight}
# label-padding-left = 5
click-left = xdotool key ctrl+alt+d

; ----------------------------------------------------------------------------------------

[module/skippy-xd]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = skippy-xd

; ----------------------------------------------------------------------------------------

[module/unplug-drive]
type = custom/script
exec = echo "󰕓"
format = <label>
label-foreground = ${colors.highlight}
click-left = unplugdrive.sh

; ----------------------------------------------------------------------------------------

[module/file-manager]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = desktop-defaults-run -fm

; ----------------------------------------------------------------------------------------

[module/icewm-manager]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = /usr/local/bin/icewm-manager-gui

; ----------------------------------------------------------------------------------------

[module/trash-bin]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = zzzfm ~/.local/share/trash/files/

; ----------------------------------------------------------------------------------------

[module/youtube]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = /opt/google/chrome/google-chrome --profile-directory=default --app-id=agimnkijcaahngcdmfeangaknmldooml

; ----------------------------------------------------------------------------------------

[module/control-center]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = antixcc.sh

; ----------------------------------------------------------------------------------------

[module/google-chrome]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = /usr/bin/google-chrome-stable

; ----------------------------------------------------------------------------------------

[module/mongodb-compass]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = /usr/bin/mongodb-compass

; ----------------------------------------------------------------------------------------

[module/postman]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = ~/postman/app/postman

; ----------------------------------------------------------------------------------------

[module/neovim]
type = custom/script
exec = echo ""
format = <label>
label-foreground = ${colors.highlight}
click-left = ~/.config/polybar/scripts/run_nvim.sh

; ----------------------------------------------------------------------------------------

[module/battery]
type = internal/battery

; this is useful in case the battery never reports 100% charge
full-at = 99

; use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = bat0
adapter = ac

; if an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; disable polling by setting the interval to 0.
;
; default: 5
poll-interval = 2

; see "man date" for details on how to format the time string
; note: if you want to use syntax tags here you need to use %%{...}
; default: %h:%m:%s
time-format = %h:%m

; available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <label-charging>
format-charging-prefix = "󰂄"
format-charging-prefix-foreground = ${colors.highlight}

; available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <label-discharging>
format-discharging-prefix = "󰁾"
format-discharging-prefix-foreground = ${colors.highlight}

; available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
format-full = <label-full>
format-full-prefix = "󰁹"
format-full-prefix-foreground = ${colors.highlight}

; available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = " %percentage%%"

; available tokens:
;   %percentage% (default)
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = " %percentage%%"

; available tokens:
;   %percentage% (default)
label-full = " full"

; only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; only applies if <bar-capacity> is used
;bar-capacity-width = 10

; only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 

; framerate in milliseconds
animation-charging-framerate = 750

; only applies if <animation-discharging> is used
;;animation-discharging-0 = ${battery.anim0}
;;animation-discharging-1 = ${battery.anim1}

; framerate in milliseconds
;animation-discharging-framerate = 500

; ----------------------------------------------------------------------------------------

; vim:ft=dosini
